### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by boxed** [mozilla/moz-sql-parser#3]
mo_testing also needs to be fixed for python3, otherwise it looks like the changes are trivial.

**Comment by klahnakoski** [comment]
I can certainly upgrade mo-testing, but I will need more time to figure out where `SQLParser` or `pyparsing` is failing on python3 (specifically, 3.6).

**Comment by klahnakoski** [comment]
I am looking into how to submit an issue to `pyparsing`; SourceForge makes it hard to submit an issue.  I signed up for the mailing list, but SourceForge makes it hard to discover the email address of the maillist.

**Comment by boxed** [comment]
Pyparsing has supported Python3 for ages.

**Comment by klahnakoski** [comment]
> Pyparsing has supported Python3 for ages.

I hope that is true.

`test001` fails because `result.items()` returns nothing.  The parse appears to have worked, but the `SQLParser` can not extract the results.  It appears `pyparsing` is not updating its internal `self.__tokdict` variable properly.

https://github.com/mozilla/moz-sql-parser/blob/d40c0ce2a361c1e70c95ee259b059c0cddfc2d5b/moz_sql_parser/__init__.py#L55

**Comment by klahnakoski** [comment]
Fixed  https://github.com/mozilla/moz-sql-parser/pull/7
