### ISSUE TITLE
"tests" should be located under the package

### ISSUE THREAD

**Issue by tolmanam** [mozilla/moz-sql-parser#32]
In its current state, PIP will install files in the following locations:
```
    ..../site-packages/moz_sql_parser-2.18.18240-py3.6.egg-info
    ..../site-packages/moz_sql_parser/*
    ..../site-packages/tests/*
```
I think the unit tests should be nested under the project.

I discovered this when I ran 'pip uninstall moz_sql_parser' and it showed me the file that were set to be removed.

**Comment by klahnakoski** [comment]
Thank you for noticing this!

I do not want `tests` under the project because the project directory gets vendored into other projects where the test/deploy/setup code is not needed.  Instead, I will ensure `tests` is not deployed:  https://github.com/klahnakoski/mo-deploy/commit/ef0f2171a54fbcadefb73bc68c61420a069128ce

Reopen this if you have a better idea.
